language: python
python:
- 3.6

git:
  depth: 1

addons:
  apt:
    packages:
      - p7zip-full

before_script:
  - export PYTHON_VERSION=cp35
  - export RELEASE_VERSION=$(curl -kL https://github.com/SeaHOH/GotoX/raw/master/local/__init__.py | grep -oP '[0-9\.]+')

script:
  - curl -kL -o cert/cacerts/mozilla.pem https://curl.haxx.se/ca/cacert.pem
  - curl -kL -o cert/cacerts/google.pem https://pki.google.com/roots.pem
  - python launcher/buildipdb.py --17mon -d

before_deploy:
  - rm -rf .git*
  - rm -rf .travis*

  - cd ..

  - git clone --depth=1 --branch=win_py_portable https://github.com/SeaHOH/GotoX.git win_py_portable

  - cp -r GotoX GotoX-non_win
  - cp -r GotoX GotoX-win32
  - mv GotoX GotoX-win_amd64

  - rm -f GotoX-non_win/*.vbs

  - cp -r win_py_portable/${PYTHON_VERSION}-win32/python GotoX-win32/python
  - mv win_py_portable/${PYTHON_VERSION}-win_amd64/python GotoX-win_amd64/python

  - zip -r GotoX-${RELEASE_VERSION}-non_win.zip GotoX-non_win/*
  - 7za a -r -mx=9 -m0=BCJ2 -m1=LZMA2:mf=bt3 -m2=LZMA:d19 -m3=LZMA:d19 -m4=LZMA:d19 -mb0s0:1 -mb0s1:2 -mb0s2:3 -mb0s3:4 GotoX-${RELEASE_VERSION}-${PYTHON_VERSION}-win32.7z GotoX-win32/*
  - 7za a -r -mx=9 -m0=BCJ2 -m1=LZMA2:mf=bt3 -m2=LZMA:d19 -m3=LZMA:d19 -m4=LZMA:d19 -mb0s0:1 -mb0s1:2 -mb0s2:3 -mb0s3:4 GotoX-${RELEASE_VERSION}-${PYTHON_VERSION}-win_amd64.7z GotoX-win_amd64/*

  - md5sum *.zip *.7z > md5sum
  - sha1sum *.zip *.7z > sha1sum

deploy:
  provider: releases
  api_key:
    secure: ${DEPLOY_TOKEN}
  file: 
    - GotoX-${RELEASE_VERSION}-non_win.zip
    - GotoX-${RELEASE_VERSION}-${PYTHON_VERSION}-win32.7z
    - GotoX-${RELEASE_VERSION}-${PYTHON_VERSION}-win_amd64.7z
    - md5sum
    - sha1sum
  skip_cleanup: true
  on:
    tags: true
    repo: SeaHOH/GotoX

notifications:
  email: false
